[mysqld]
datadir='C:/Users/gabri/Code/Briel comics website/briel-comics/database/mysql_files/data'
port=3307
enable-named-pipe
socket=MYSQL_breel
secure_file_priv='C:/Users/gabri/Code/Briel comics website/briel-comics/database/mysql_files/uploads'